# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PizzaStore(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, pizza_stores_id: int=None, store_name: str=None, store_location: str=None, specials: List[int]=None):  # noqa: E501
        """PizzaStore - a model defined in Swagger

        :param pizza_stores_id: The pizza_stores_id of this PizzaStore.  # noqa: E501
        :type pizza_stores_id: int
        :param store_name: The store_name of this PizzaStore.  # noqa: E501
        :type store_name: str
        :param store_location: The store_location of this PizzaStore.  # noqa: E501
        :type store_location: str
        :param specials: The specials of this PizzaStore.  # noqa: E501
        :type specials: List[int]
        """
        self.swagger_types = {
            'pizza_stores_id': int,
            'store_name': str,
            'store_location': str,
            'specials': List[int]
        }

        self.attribute_map = {
            'pizza_stores_id': 'pizza_stores_id',
            'store_name': 'store_name',
            'store_location': 'store_location',
            'specials': 'specials'
        }
        self._pizza_stores_id = pizza_stores_id
        self._store_name = store_name
        self._store_location = store_location
        self._specials = specials

    @classmethod
    def from_dict(cls, dikt) -> 'PizzaStore':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PizzaStore of this PizzaStore.  # noqa: E501
        :rtype: PizzaStore
        """
        return util.deserialize_model(dikt, cls)

    @property
    def pizza_stores_id(self) -> int:
        """Gets the pizza_stores_id of this PizzaStore.

        The id of a pizza store.   # noqa: E501

        :return: The pizza_stores_id of this PizzaStore.
        :rtype: int
        """
        return self._pizza_stores_id

    @pizza_stores_id.setter
    def pizza_stores_id(self, pizza_stores_id: int):
        """Sets the pizza_stores_id of this PizzaStore.

        The id of a pizza store.   # noqa: E501

        :param pizza_stores_id: The pizza_stores_id of this PizzaStore.
        :type pizza_stores_id: int
        """

        self._pizza_stores_id = pizza_stores_id

    @property
    def store_name(self) -> str:
        """Gets the store_name of this PizzaStore.

        The name of a pizza store.   # noqa: E501

        :return: The store_name of this PizzaStore.
        :rtype: str
        """
        return self._store_name

    @store_name.setter
    def store_name(self, store_name: str):
        """Sets the store_name of this PizzaStore.

        The name of a pizza store.   # noqa: E501

        :param store_name: The store_name of this PizzaStore.
        :type store_name: str
        """

        self._store_name = store_name

    @property
    def store_location(self) -> str:
        """Gets the store_location of this PizzaStore.

        The location of a pizza store.   # noqa: E501

        :return: The store_location of this PizzaStore.
        :rtype: str
        """
        return self._store_location

    @store_location.setter
    def store_location(self, store_location: str):
        """Sets the store_location of this PizzaStore.

        The location of a pizza store.   # noqa: E501

        :param store_location: The store_location of this PizzaStore.
        :type store_location: str
        """

        self._store_location = store_location

    @property
    def specials(self) -> List[int]:
        """Gets the specials of this PizzaStore.

        The IDs of pizza specials that the store currently offers.   # noqa: E501

        :return: The specials of this PizzaStore.
        :rtype: List[int]
        """
        return self._specials

    @specials.setter
    def specials(self, specials: List[int]):
        """Sets the specials of this PizzaStore.

        The IDs of pizza specials that the store currently offers.   # noqa: E501

        :param specials: The specials of this PizzaStore.
        :type specials: List[int]
        """

        self._specials = specials
